import os
import sys

import lit.formats

# Generated by `dpm trace test --init`. Integration tests run against the live
# Canton node that `dpm trace test --integration` boots; connection details
# arrive via DPM_TRACE_IT_* environment variables.
config.name = "dpm-trace-integration"
config.test_format = lit.formats.ShTest(execute_external=True)  # real /bin/sh: $(...) etc.
config.suffixes = [".test"]
config.excludes = ["demos"]
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = os.path.join(config.test_source_root, ".lit")

# The runner exports DPM_TRACE_IT_* before invoking lit. If they are missing the
# suite was started without a live Canton (e.g. plain `lit`); fail loudly rather
# than skip, so a mis-wired runner can never go green with zero tests run.
ledger = os.environ.get("DPM_TRACE_IT_LEDGER")
if not ledger:
    lit_config.fatal(
        "integration tests need a live Canton; run them with "
        "`dpm trace test --integration <dir>` (DPM_TRACE_IT_LEDGER is not set)."
    )

python = os.environ.get("DPM_TRACE_IT_PYTHON", sys.executable)
config.environment["PYTHONPATH"] = os.environ.get("DPM_TRACE_IT_SRC", "")

# lit sanitizes the environment, so an instrumented (`go build -cover`) %dpm
# would find GOCOVERDIR unset, warn on stderr and corrupt the output these
# tests compare. Forwarded only when present.
if os.environ.get("GOCOVERDIR"):
    config.environment["GOCOVERDIR"] = os.environ["GOCOVERDIR"]

# %dpm is the dpm-trace binary, supplied by the runner. There is no fallback:
# running the suite against something else silently would be worse than
# refusing to start.
dpm = os.environ.get("DPM_TRACE_IT_DPM")
if not dpm:
    lit_config.fatal(
        "DPM_TRACE_IT_DPM is not set; run this suite through "
        "`dpm trace test --integration <dir>`")

config.substitutions.append(("%daml-yaml", os.environ.get("DPM_TRACE_IT_DAML_YAML", "")))
config.substitutions.append(("%damlc", os.environ.get("DPM_TRACE_IT_DAML", "daml")))
# %ledger2 must precede %ledger -- otherwise "%ledger" matches inside "%ledger2".
config.substitutions.append(("%ledger2", os.environ.get("DPM_TRACE_IT_LEDGER2", "")))
config.substitutions.append(("%ledger", ledger))
config.substitutions.append(("%issuer", os.environ.get("DPM_TRACE_IT_ISSUER", "")))
config.substitutions.append(("%alice", os.environ.get("DPM_TRACE_IT_ALICE", "")))
config.substitutions.append(("%bob", os.environ.get("DPM_TRACE_IT_BOB", "")))
config.substitutions.append(("%dar", os.environ.get("DPM_TRACE_IT_DAR", "")))
config.substitutions.append(("%python", python))
config.substitutions.append(("%dpm", dpm))
