import os
import sys

import lit.formats

# Generated by `dpm trace test --init`. Integration tests run against the live
# Canton node that `dpm trace test --integration` boots; connection details
# arrive via DPM_TRACE_IT_* environment variables.
config.name = "dpm-trace-integration"
config.test_format = lit.formats.ShTest(execute_external=True)  # real /bin/sh: $(...) etc.
config.suffixes = [".test"]
config.test_source_root = os.path.dirname(__file__)
config.test_exec_root = os.path.join(config.test_source_root, ".lit")

# The runner exports DPM_TRACE_IT_* before invoking lit. If they are missing the
# suite was started without a live Canton (e.g. plain `lit`); fail loudly rather
# than skip, so a mis-wired runner can never go green with zero tests run.
ledger = os.environ.get("DPM_TRACE_IT_LEDGER")
if not ledger:
    lit_config.fatal(
        "integration tests need a live Canton; run them with "
        "`dpm trace test --integration <dir>` (DPM_TRACE_IT_LEDGER is not set)."
    )

python = os.environ.get("DPM_TRACE_IT_PYTHON", sys.executable)
config.environment["PYTHONPATH"] = os.environ.get("DPM_TRACE_IT_SRC", "")

config.substitutions.append(("%daml-yaml", os.environ.get("DPM_TRACE_IT_DAML_YAML", "")))
config.substitutions.append(("%damlc", os.environ.get("DPM_TRACE_IT_DAML", "daml")))
# %ledger2 must precede %ledger -- otherwise "%ledger" matches inside "%ledger2".
config.substitutions.append(("%ledger2", os.environ.get("DPM_TRACE_IT_LEDGER2", "")))
config.substitutions.append(("%ledger", ledger))
config.substitutions.append(("%alice", os.environ.get("DPM_TRACE_IT_ALICE", "")))
config.substitutions.append(("%bob", os.environ.get("DPM_TRACE_IT_BOB", "")))
config.substitutions.append(("%dar", os.environ.get("DPM_TRACE_IT_DAR", "")))
config.substitutions.append(("%python", python))
config.substitutions.append(("%dpm", python + " -m dpm_trace.cli"))
